### ISSUE TITLE
(Feature Request) Adding error handler in the methods for the base repository.

### ISSUE THREAD

**Issue by vaidikkamde** [krsbx/prisma-repo-next#45]
For the methods in base repository can we add an error handler/ try catch block to return the error to be handled by the function/ method calling it.

**Comment by krsbx** [comment]
@vaidikkamde  regarding this feature, we can just modified the `baseRepository.ts` file without worrying it to be overwritten by the generator

**Comment by vaidikkamde** [comment]
Okay would do that but it would be nice if the generator by default added the error catch. Will take some time out to make a PR for that if you want. Also thanks for the awesome generator it is greatly helping my team.

**Comment by krsbx** [comment]
@vaidikkamde thank you, if you want to add that features you could create a PR and it would be awesome

but, probably add some sort of config so the others could chose whether they want to use the throw one or not
